FROM jorza/nova-dev-base:focal AS builder

WORKDIR /home/nova-dev/setup-scripts

# Start with non-git-dependent scripts
COPY ./setup-scripts/scripts-0 ./scripts-0
RUN ./scripts-0/1-title.sh
RUN ./scripts-0/2.1-ros2.sh
#RUN ./scripts-0/2.2-cameras.sh  # Exclude cameras, doesn't work
RUN ./scripts-0/2.3-net-tools.sh
#RUN ./scripts-0/2.4-gui.sh  # Exclude GUI, doesn't work

# Add the builder's SSH info for use with git
COPY ./.ssh /home/nova-dev/.ssh

# Run git-dependent scripts
COPY ./setup-scripts/scripts-1 ./scripts-1
RUN ./scripts-1/3.0-git.sh; exit 0
RUN ./scripts-1/3.1-arm-model-dependencies.sh
RUN ./scripts-1/4.0-workspace.sh
RUN ./scripts-1/4.1-git-additional-repos.sh
#RUN ./scripts-1/5-gui-packages.sh  # Exclude GUI, doesn't work
RUN ./scripts-1/6-end.sh

# Remove unwanted files
RUN sudo rm -rf /home/nova-dev/.ssh/*
RUN sudo rm -rf /home/nova-dev/setup-scripts

# Copy the current state to the final image
# Ensures builder's SSH info is not in the final image
FROM jorza/nova-dev-base:focal

COPY --from=builder / /
