version: "3.8"

services:
  nova-dev-base:
    image: jorza/nova-dev-base:focal
    volumes:
      # For source code
      - ../../nova_ws:/home/nova-dev/nova_ws
      # SSH info for git
      - ./.ssh:/home/nova-dev/.ssh
    container_name: nova-dev-base
    tty: true
